---
- name: Deploy Angular app using Docker
  hosts: all
  become: true
  tasks:
    - name: Remove any conflicting Docker repository entries
      command: "sudo rm -f /etc/apt/sources.list.d/docker.list"
      ignore_errors: true

    - name: Remove conflicting containerd packages (if installed)
      apt:
        name:
          - containerd.io
          - containerd
        state: absent
      ignore_errors: true

    - name: Ensure Docker dependencies are installed
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker's official GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /usr/share/keyrings/docker-archive-keyring.gpg
        mode: '0644'

    - name: Add Docker's official repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present
        filename: "docker"

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Docker and dependencies
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Ensure Docker service is enabled and started
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Install Ansible (if needed)
      apt:
        name: ansible
        state: present
